// Standard addresses/routes for trip creation
export const STANDARD_ROUTES = [
  'Toshkent',
  'Samarqand',
  'Buxoro',
  'Andijon',
  'Farg\'ona',
  'Namangan',
  'Qarshi',
  'Nukus',
  'Termiz',
  'Guliston',
  'Jizzax',
  'Navoiy',
  'Urganch',
  'Qo\'qon',
  'Marg\'ilon',
  'Angren',
  'Olmaliq',
  'Bekobod',
  'Chirchiq',
  'Denov',
  'Koson',
  'Shahrisabz',
  'Kitob',
  'Kattaqo\'rg\'on',
  'Zomin',
  'Uchqo\'rg\'on',
  'Asaka',
  'Qo\'ng\'irot',
  'Muborak',
  'G\'uzor',
];

// Vehicle types
export const VEHICLE_TYPES = [
  'Umumiy taksi',
  'Chevrolet Malibu',
  'Chevrolet Cobalt',
  'Chevrolet Spark',
  'Chevrolet Nexia',
  'Chevrolet Lacetti',
  'Chevrolet Captiva',
  'Chevrolet Tracker',
  'Chevrolet Equinox',
  'Chevrolet Tahoe',
  'Chevrolet Suburban',
  'Toyota Camry',
  'Toyota Corolla',
  'Toyota RAV4',
  'Toyota Land Cruiser',
  'Toyota Highlander',
  'Honda Accord',
  'Honda Civic',
  'Honda CR-V',
  'Hyundai Sonata',
  'Hyundai Elantra',
  'Hyundai Tucson',
  'Hyundai Santa Fe',
  'Kia Optima',
  'Kia Rio',
  'Kia Sportage',
  'Nissan Altima',
  'Nissan Sentra',
  'Nissan X-Trail',
  'Ford Focus',
  'Ford Mondeo',
  'Ford Explorer',
  'BMW 3 Series',
  'BMW 5 Series',
  'Mercedes-Benz C-Class',
  'Mercedes-Benz E-Class',
  'Audi A4',
  'Audi A6',
  'Volkswagen Passat',
  'Volkswagen Jetta',
  'Skoda Octavia',
  'Skoda Superb',
  'Boshqa',
];
